2014/02/11 11:38:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "index" was not found.' in /home/vadim/yii/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /home/vadim/yii/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('index')
#1 /home/vadim/yii/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /home/vadim/yii/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /home/vadim/yii/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /home/vadim/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /home/vadim/yii/framework/web/CWebApplication.php(282): CController->run('page')
#6 /home/vadim/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /home/vadim/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /home/vadim/projects/www/yiitest/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/site/page
---
2014/02/11 11:39:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "index" was not found.' in /home/vadim/yii/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /home/vadim/yii/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('index')
#1 /home/vadim/yii/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /home/vadim/yii/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /home/vadim/yii/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /home/vadim/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /home/vadim/yii/framework/web/CWebApplication.php(282): CController->run('page')
#6 /home/vadim/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /home/vadim/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /home/vadim/projects/www/yiitest/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/site/page
---
2014/02/11 11:39:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "index" was not found.' in /home/vadim/yii/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /home/vadim/yii/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('index')
#1 /home/vadim/yii/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /home/vadim/yii/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /home/vadim/yii/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /home/vadim/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /home/vadim/yii/framework/web/CWebApplication.php(282): CController->run('page')
#6 /home/vadim/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /home/vadim/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /home/vadim/projects/www/yiitest/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/site/page
---
2014/02/11 11:45:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "page".' in /home/vadim/yii/framework/web/CController.php:483
Stack trace:
#0 /home/vadim/yii/framework/web/CController.php(270): CController->missingAction('page')
#1 /home/vadim/yii/framework/web/CWebApplication.php(282): CController->run('page')
#2 /home/vadim/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#3 /home/vadim/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /home/vadim/projects/www/yiitest/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/page?view=about
HTTP_REFERER=http://localhost:8000/index.php/site/index
---
2014/02/11 11:45:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "contact".' in /home/vadim/yii/framework/web/CController.php:483
Stack trace:
#0 /home/vadim/yii/framework/web/CController.php(270): CController->missingAction('contact')
#1 /home/vadim/yii/framework/web/CWebApplication.php(282): CController->run('contact')
#2 /home/vadim/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/contact')
#3 /home/vadim/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /home/vadim/projects/www/yiitest/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/contact
HTTP_REFERER=http://localhost:8000/index.php/site/index
---
2014/02/11 11:45:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "login".' in /home/vadim/yii/framework/web/CController.php:483
Stack trace:
#0 /home/vadim/yii/framework/web/CController.php(270): CController->missingAction('login')
#1 /home/vadim/yii/framework/web/CWebApplication.php(282): CController->run('login')
#2 /home/vadim/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#3 /home/vadim/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /home/vadim/projects/www/yiitest/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/login
HTTP_REFERER=http://localhost:8000/index.php/site/contact
---
2014/02/11 11:49:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "users".' in /home/vadim/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /home/vadim/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('users')
#1 /home/vadim/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /home/vadim/projects/www/yiitest/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/users
---
2014/02/11 11:49:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "users/index".' in /home/vadim/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /home/vadim/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('users/index')
#1 /home/vadim/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /home/vadim/projects/www/yiitest/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/users/index
---
2014/02/11 11:49:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "users/index".' in /home/vadim/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /home/vadim/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('users/index')
#1 /home/vadim/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /home/vadim/projects/www/yiitest/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/users/index
---
2014/02/11 11:50:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "users/index".' in /home/vadim/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /home/vadim/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('users/index')
#1 /home/vadim/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /home/vadim/projects/www/yiitest/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/users/index
---
2014/02/11 11:50:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "users/index".' in /home/vadim/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /home/vadim/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('users/index')
#1 /home/vadim/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /home/vadim/projects/www/yiitest/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/users/index
---
2014/02/11 11:50:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "users/index".' in /home/vadim/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /home/vadim/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('users/index')
#1 /home/vadim/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /home/vadim/projects/www/yiitest/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/users/index
---
2014/02/11 11:50:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "users/index".' in /home/vadim/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /home/vadim/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('users/index')
#1 /home/vadim/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /home/vadim/projects/www/yiitest/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/users/index
---
2014/02/11 11:50:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "users/index".' in /home/vadim/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /home/vadim/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('users/index')
#1 /home/vadim/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /home/vadim/projects/www/yiitest/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/users/index
---
2014/02/11 11:50:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "users".' in /home/vadim/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /home/vadim/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('users')
#1 /home/vadim/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /home/vadim/projects/www/yiitest/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/users
---
2014/02/11 11:50:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "users/index".' in /home/vadim/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /home/vadim/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('users/index')
#1 /home/vadim/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /home/vadim/projects/www/yiitest/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/users/index
---
2014/02/11 11:50:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "users".' in /home/vadim/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /home/vadim/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('users')
#1 /home/vadim/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /home/vadim/projects/www/yiitest/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/users
---
2014/02/11 11:51:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "users".' in /home/vadim/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /home/vadim/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('users')
#1 /home/vadim/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /home/vadim/projects/www/yiitest/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/users
---
2014/02/11 11:51:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "users".' in /home/vadim/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /home/vadim/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('users')
#1 /home/vadim/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /home/vadim/projects/www/yiitest/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/users
---
2014/02/11 11:51:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "users".' in /home/vadim/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /home/vadim/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('users')
#1 /home/vadim/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /home/vadim/projects/www/yiitest/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/users
---
2014/02/11 11:51:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "users".' in /home/vadim/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /home/vadim/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('users')
#1 /home/vadim/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /home/vadim/projects/www/yiitest/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/users
---
2014/02/11 11:51:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "users".' in /home/vadim/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /home/vadim/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('users')
#1 /home/vadim/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /home/vadim/projects/www/yiitest/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/users
---
2014/02/11 11:51:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "users".' in /home/vadim/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /home/vadim/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('users')
#1 /home/vadim/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /home/vadim/projects/www/yiitest/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/users
---
2014/02/11 12:35:48 [error] [php] Undefined variable: country (/home/vadim/projects/www/yiitest/protected/views/address/countries.php:2)
Stack trace:
#0 /home/vadim/yii/framework/web/CController.php(869): AddressController->renderFile()
#1 /home/vadim/yii/framework/web/CController.php(782): AddressController->renderPartial()
#2 /home/vadim/projects/www/yiitest/protected/controllers/AddressController.php(7): AddressController->render()
#3 /home/vadim/yii/framework/web/actions/CInlineAction.php(49): AddressController->actionCountries()
#4 /home/vadim/yii/framework/web/CController.php(308): CInlineAction->runWithParams()
#5 /home/vadim/yii/framework/web/CController.php(286): AddressController->runAction()
#6 /home/vadim/yii/framework/web/CController.php(265): AddressController->runActionWithFilters()
#7 /home/vadim/yii/framework/web/CWebApplication.php(282): AddressController->run()
#8 /home/vadim/yii/framework/web/CWebApplication.php(141): CWebApplication->runController()
#9 /home/vadim/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /home/vadim/projects/www/yiitest/index.php(13): CWebApplication->run()
REQUEST_URI=/address/countries
in /home/vadim/projects/www/yiitest/protected/views/address/countries.php (2)
in /home/vadim/projects/www/yiitest/protected/controllers/AddressController.php (7)
in /home/vadim/projects/www/yiitest/index.php (13)
2014/02/11 12:32:51 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yiitest.tbl_migration' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `tbl_migration`.
2014/02/11 12:36:21 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'string(32) NOT NULL,
	`password` string(32) NOT NULL
)' at line 3. The SQL statement executed was: CREATE TABLE `users` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`login` string(32) NOT NULL,
	`password` string(32) NOT NULL
).
2014/02/11 12:36:21 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'string(32) NOT NULL,
	`password` string(32) NOT NULL
)' at line 3. The SQL statement executed was: CREATE TABLE `users` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`login` string(32) NOT NULL,
	`password` string(32) NOT NULL
)' in /home/vadim/yii/framework/db/CDbCommand.php:358
Stack trace:
#0 /home/vadim/yii/framework/db/CDbCommand.php(1324): CDbCommand->execute()
#1 /home/vadim/yii/framework/db/CDbMigration.php(233): CDbCommand->createTable('users', Array, NULL)
#2 /home/vadim/projects/www/yiitest/protected/migrations/m140211_095205_create_users_table.php(10): CDbMigration->createTable('users', Array)
#3 /home/vadim/yii/framework/cli/commands/MigrateCommand.php(385): m140211_095205_create_users_table->up()
#4 /home/vadim/yii/framework/cli/commands/MigrateCommand.php(109): MigrateCommand->migrateUp('m140211_095205_...')
#5 [internal function]: MigrateCommand->actionUp(Array)
#6 /home/vadim/yii/framework/console/CConsoleCommand.php(172): ReflectionMethod->invokeArgs(Object(MigrateCommand), Array)
#7 /home/vadim/yii/framework/console/CConsoleCommandRunner.php(71): CConsoleCommand->run(Array)
#8 /home/vadim/yii/framework/console/CConsoleApplication.php(92): CConsoleCommandRunner->run(Array)
#9 /home/vadim/yii/framework/base/CApplication.php(180): CConsoleApplication->processRequest()
#10 /home/vadim/yii/framework/yiic.php(33): CApplication->run()
#11 /home/vadim/projects/www/yiitest/protected/yiic.php(7): require_once('/home/vadim/yii...')
#12 /home/vadim/projects/www/yiitest/protected/yiic(4): require_once('/home/vadim/pro...')
#13 {main}
---
2014/02/11 12:36:27 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'string(32) NOT NULL,
	`password` string(32) NOT NULL
)' at line 3. The SQL statement executed was: CREATE TABLE `users` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`login` string(32) NOT NULL,
	`password` string(32) NOT NULL
).
2014/02/11 12:36:27 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'string(32) NOT NULL,
	`password` string(32) NOT NULL
)' at line 3. The SQL statement executed was: CREATE TABLE `users` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`login` string(32) NOT NULL,
	`password` string(32) NOT NULL
)' in /home/vadim/yii/framework/db/CDbCommand.php:358
Stack trace:
#0 /home/vadim/yii/framework/db/CDbCommand.php(1324): CDbCommand->execute()
#1 /home/vadim/yii/framework/db/CDbMigration.php(233): CDbCommand->createTable('users', Array, NULL)
#2 /home/vadim/projects/www/yiitest/protected/migrations/m140211_095205_create_users_table.php(10): CDbMigration->createTable('users', Array)
#3 /home/vadim/yii/framework/cli/commands/MigrateCommand.php(385): m140211_095205_create_users_table->up()
#4 /home/vadim/yii/framework/cli/commands/MigrateCommand.php(109): MigrateCommand->migrateUp('m140211_095205_...')
#5 [internal function]: MigrateCommand->actionUp(Array)
#6 /home/vadim/yii/framework/console/CConsoleCommand.php(172): ReflectionMethod->invokeArgs(Object(MigrateCommand), Array)
#7 /home/vadim/yii/framework/console/CConsoleCommandRunner.php(71): CConsoleCommand->run(Array)
#8 /home/vadim/yii/framework/console/CConsoleApplication.php(92): CConsoleCommandRunner->run(Array)
#9 /home/vadim/yii/framework/base/CApplication.php(180): CConsoleApplication->processRequest()
#10 /home/vadim/yii/framework/yiic.php(33): CApplication->run()
#11 /home/vadim/projects/www/yiitest/protected/yiic.php(7): require_once('/home/vadim/yii...')
#12 /home/vadim/projects/www/yiitest/protected/yiic(4): require_once('/home/vadim/pro...')
#13 {main}
---
2014/02/11 12:37:05 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'string(32) NOT NULL,
	`password` string(32) NOT NULL
)' at line 3. The SQL statement executed was: CREATE TABLE `users` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`login` string(32) NOT NULL,
	`password` string(32) NOT NULL
).
2014/02/11 12:37:05 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'string(32) NOT NULL,
	`password` string(32) NOT NULL
)' at line 3. The SQL statement executed was: CREATE TABLE `users` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`login` string(32) NOT NULL,
	`password` string(32) NOT NULL
)' in /home/vadim/yii/framework/db/CDbCommand.php:358
Stack trace:
#0 /home/vadim/yii/framework/db/CDbCommand.php(1324): CDbCommand->execute()
#1 /home/vadim/yii/framework/db/CDbMigration.php(233): CDbCommand->createTable('users', Array, NULL)
#2 /home/vadim/projects/www/yiitest/protected/migrations/m140211_095205_create_users_table.php(10): CDbMigration->createTable('users', Array)
#3 /home/vadim/yii/framework/cli/commands/MigrateCommand.php(385): m140211_095205_create_users_table->up()
#4 /home/vadim/yii/framework/cli/commands/MigrateCommand.php(109): MigrateCommand->migrateUp('m140211_095205_...')
#5 [internal function]: MigrateCommand->actionUp(Array)
#6 /home/vadim/yii/framework/console/CConsoleCommand.php(172): ReflectionMethod->invokeArgs(Object(MigrateCommand), Array)
#7 /home/vadim/yii/framework/console/CConsoleCommandRunner.php(71): CConsoleCommand->run(Array)
#8 /home/vadim/yii/framework/console/CConsoleApplication.php(92): CConsoleCommandRunner->run(Array)
#9 /home/vadim/yii/framework/base/CApplication.php(180): CConsoleApplication->processRequest()
#10 /home/vadim/yii/framework/yiic.php(33): CApplication->run()
#11 /home/vadim/projects/www/yiitest/protected/yiic.php(7): require_once('/home/vadim/yii...')
#12 /home/vadim/projects/www/yiitest/protected/yiic(4): require_once('/home/vadim/pro...')
#13 {main}
---
2014/02/11 12:42:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "city".' in /home/vadim/yii/framework/web/CController.php:483
Stack trace:
#0 /home/vadim/yii/framework/web/CController.php(270): CController->missingAction('city')
#1 /home/vadim/yii/framework/web/CWebApplication.php(282): CController->run('city')
#2 /home/vadim/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('address/city')
#3 /home/vadim/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /home/vadim/projects/www/yiitest/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/address/countries/1
---
2014/02/11 12:42:57 [error] [php] Undefined variable: countries (/home/vadim/projects/www/yiitest/protected/views/address/cities.php:1)
Stack trace:
#0 /home/vadim/yii/framework/web/CController.php(869): AddressController->renderFile()
#1 /home/vadim/yii/framework/web/CController.php(782): AddressController->renderPartial()
#2 /home/vadim/projects/www/yiitest/protected/controllers/AddressController.php(11): AddressController->render()
#3 /home/vadim/yii/framework/web/actions/CInlineAction.php(49): AddressController->actionCities()
#4 /home/vadim/yii/framework/web/CController.php(308): CInlineAction->runWithParams()
#5 /home/vadim/yii/framework/web/CController.php(286): AddressController->runAction()
#6 /home/vadim/yii/framework/web/CController.php(265): AddressController->runActionWithFilters()
#7 /home/vadim/yii/framework/web/CWebApplication.php(282): AddressController->run()
#8 /home/vadim/yii/framework/web/CWebApplication.php(141): CWebApplication->runController()
#9 /home/vadim/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /home/vadim/projects/www/yiitest/index.php(13): CWebApplication->run()
REQUEST_URI=/address/countries/1
in /home/vadim/projects/www/yiitest/protected/views/address/cities.php (1)
in /home/vadim/projects/www/yiitest/protected/controllers/AddressController.php (11)
in /home/vadim/projects/www/yiitest/index.php (13)
2014/02/11 12:57:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "address/countries".' in /home/vadim/yii/framework/web/CUrlManager.php:374
Stack trace:
#0 /home/vadim/yii/framework/web/CWebApplication.php(140): CUrlManager->parseUrl(Object(CHttpRequest))
#1 /home/vadim/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /home/vadim/projects/www/yiitest/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/address/countries/
---
2014/02/11 12:57:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "".' in /home/vadim/yii/framework/web/CUrlManager.php:374
Stack trace:
#0 /home/vadim/yii/framework/web/CWebApplication.php(140): CUrlManager->parseUrl(Object(CHttpRequest))
#1 /home/vadim/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /home/vadim/projects/www/yiitest/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/
---
2014/02/17 13:38:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/register".' in /home/vadim/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /home/vadim/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('user/register')
#1 /home/vadim/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /home/vadim/projects/www/yiitest/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/user/register
---
2014/02/17 13:38:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/register".' in /home/vadim/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /home/vadim/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('user/register')
#1 /home/vadim/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /home/vadim/projects/www/yiitest/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/user/register
---
2014/02/17 13:39:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/register".' in /home/vadim/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /home/vadim/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('user/register')
#1 /home/vadim/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /home/vadim/projects/www/yiitest/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/user/register
---
2014/02/17 13:39:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "users/register".' in /home/vadim/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /home/vadim/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('users/register')
#1 /home/vadim/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /home/vadim/projects/www/yiitest/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/users/register
---
2014/02/17 13:39:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/register".' in /home/vadim/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /home/vadim/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('user/register')
#1 /home/vadim/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /home/vadim/projects/www/yiitest/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/user/register
---
2014/02/17 13:40:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "login".' in /home/vadim/yii/framework/web/CController.php:483
Stack trace:
#0 /home/vadim/yii/framework/web/CController.php(270): CController->missingAction('login')
#1 /home/vadim/yii/framework/web/CWebApplication.php(282): CController->run('login')
#2 /home/vadim/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('user/login')
#3 /home/vadim/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /home/vadim/projects/www/yiitest/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/login
---
2014/02/17 13:57:20 [error] [php] include(UserForm.php): failed to open stream: No such file or directory (/home/vadim/yii/framework/YiiBase.php:427)
Stack trace:
#0 /home/vadim/projects/www/yiitest/protected/controllers/UserController.php(14): spl_autoload_call()
#1 /home/vadim/yii/framework/web/actions/CInlineAction.php(49): UserController->actionRegister()
#2 /home/vadim/yii/framework/web/CController.php(308): CInlineAction->runWithParams()
#3 /home/vadim/yii/framework/web/CController.php(286): UserController->runAction()
#4 /home/vadim/yii/framework/web/CController.php(265): UserController->runActionWithFilters()
#5 /home/vadim/yii/framework/web/CWebApplication.php(282): UserController->run()
#6 /home/vadim/yii/framework/web/CWebApplication.php(141): CWebApplication->runController()
#7 /home/vadim/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /home/vadim/projects/www/yiitest/index.php(13): CWebApplication->run()
REQUEST_URI=/register
in /home/vadim/projects/www/yiitest/protected/controllers/UserController.php (14)
in /home/vadim/projects/www/yiitest/index.php (13)
2014/02/17 13:57:21 [error] [php] include(UserForm.php): failed to open stream: No such file or directory (/home/vadim/yii/framework/YiiBase.php:427)
Stack trace:
#0 /home/vadim/projects/www/yiitest/protected/controllers/UserController.php(14): spl_autoload_call()
#1 /home/vadim/yii/framework/web/actions/CInlineAction.php(49): UserController->actionRegister()
#2 /home/vadim/yii/framework/web/CController.php(308): CInlineAction->runWithParams()
#3 /home/vadim/yii/framework/web/CController.php(286): UserController->runAction()
#4 /home/vadim/yii/framework/web/CController.php(265): UserController->runActionWithFilters()
#5 /home/vadim/yii/framework/web/CWebApplication.php(282): UserController->run()
#6 /home/vadim/yii/framework/web/CWebApplication.php(141): CWebApplication->runController()
#7 /home/vadim/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /home/vadim/projects/www/yiitest/index.php(13): CWebApplication->run()
REQUEST_URI=/register
in /home/vadim/projects/www/yiitest/protected/controllers/UserController.php (14)
in /home/vadim/projects/www/yiitest/index.php (13)
2014/02/17 14:06:50 [error] [exception.CException] exception 'CException' with message 'Property "UserForm.repeat_password" is not defined.' in /home/vadim/yii/framework/base/CComponent.php:130
Stack trace:
#0 /home/vadim/yii/framework/web/helpers/CHtml.php(2529): CComponent->__get('repeat_password')
#1 /home/vadim/yii/framework/web/helpers/CHtml.php(2252): CHtml::resolveValue(Object(UserForm), 'repeat_password')
#2 /home/vadim/yii/framework/web/helpers/CHtml.php(1628): CHtml::activeInputField('password', Object(UserForm), 'repeat_password', Array)
#3 /home/vadim/projects/www/yiitest/protected/views/user/register.php(14): CHtml::activePasswordField(Object(UserForm), 'repeat_password')
#4 /home/vadim/yii/framework/web/CBaseController.php(126): require('/home/vadim/pro...')
#5 /home/vadim/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal('/home/vadim/pro...', Array, true)
#6 /home/vadim/yii/framework/web/CController.php(869): CBaseController->renderFile('/home/vadim/pro...', Array, true)
#7 /home/vadim/yii/framework/web/CController.php(782): CController->renderPartial('register', Array, true)
#8 /home/vadim/projects/www/yiitest/protected/controllers/UserController.php(25): CController->render('register', Array)
#9 /home/vadim/yii/framework/web/actions/CInlineAction.php(49): UserController->actionRegister()
#10 /home/vadim/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#11 /home/vadim/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#12 /home/vadim/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 /home/vadim/yii/framework/web/CWebApplication.php(282): CController->run('register')
#14 /home/vadim/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('user/register')
#15 /home/vadim/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#16 /home/vadim/projects/www/yiitest/index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/register
---
2014/02/17 14:07:02 [error] [exception.CException] exception 'CException' with message 'Property "UserForm.repeat_password" is not defined.' in /home/vadim/yii/framework/base/CComponent.php:130
Stack trace:
#0 /home/vadim/yii/framework/web/helpers/CHtml.php(2529): CComponent->__get('repeat_password')
#1 /home/vadim/yii/framework/web/helpers/CHtml.php(2252): CHtml::resolveValue(Object(UserForm), 'repeat_password')
#2 /home/vadim/yii/framework/web/helpers/CHtml.php(1628): CHtml::activeInputField('password', Object(UserForm), 'repeat_password', Array)
#3 /home/vadim/projects/www/yiitest/protected/views/user/register.php(14): CHtml::activePasswordField(Object(UserForm), 'repeat_password')
#4 /home/vadim/yii/framework/web/CBaseController.php(126): require('/home/vadim/pro...')
#5 /home/vadim/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal('/home/vadim/pro...', Array, true)
#6 /home/vadim/yii/framework/web/CController.php(869): CBaseController->renderFile('/home/vadim/pro...', Array, true)
#7 /home/vadim/yii/framework/web/CController.php(782): CController->renderPartial('register', Array, true)
#8 /home/vadim/projects/www/yiitest/protected/controllers/UserController.php(25): CController->render('register', Array)
#9 /home/vadim/yii/framework/web/actions/CInlineAction.php(49): UserController->actionRegister()
#10 /home/vadim/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#11 /home/vadim/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#12 /home/vadim/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 /home/vadim/yii/framework/web/CWebApplication.php(282): CController->run('register')
#14 /home/vadim/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('user/register')
#15 /home/vadim/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#16 /home/vadim/projects/www/yiitest/index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/register
---
2014/02/17 14:07:16 [error] [exception.CException] exception 'CException' with message 'Property "UserForm.repeat_password" is not defined.' in /home/vadim/yii/framework/base/CComponent.php:130
Stack trace:
#0 /home/vadim/yii/framework/web/helpers/CHtml.php(2529): CComponent->__get('repeat_password')
#1 /home/vadim/yii/framework/web/helpers/CHtml.php(2252): CHtml::resolveValue(Object(UserForm), 'repeat_password')
#2 /home/vadim/yii/framework/web/helpers/CHtml.php(1628): CHtml::activeInputField('password', Object(UserForm), 'repeat_password', Array)
#3 /home/vadim/projects/www/yiitest/protected/views/user/register.php(14): CHtml::activePasswordField(Object(UserForm), 'repeat_password')
#4 /home/vadim/yii/framework/web/CBaseController.php(126): require('/home/vadim/pro...')
#5 /home/vadim/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal('/home/vadim/pro...', Array, true)
#6 /home/vadim/yii/framework/web/CController.php(869): CBaseController->renderFile('/home/vadim/pro...', Array, true)
#7 /home/vadim/yii/framework/web/CController.php(782): CController->renderPartial('register', Array, true)
#8 /home/vadim/projects/www/yiitest/protected/controllers/UserController.php(25): CController->render('register', Array)
#9 /home/vadim/yii/framework/web/actions/CInlineAction.php(49): UserController->actionRegister()
#10 /home/vadim/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#11 /home/vadim/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#12 /home/vadim/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 /home/vadim/yii/framework/web/CWebApplication.php(282): CController->run('register')
#14 /home/vadim/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('user/register')
#15 /home/vadim/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#16 /home/vadim/projects/www/yiitest/index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/register
---
2014/02/17 14:09:46 [error] [exception.CException] exception 'CException' with message 'Property "UserForm.repeat_password" is not defined.' in /home/vadim/yii/framework/base/CComponent.php:130
Stack trace:
#0 /home/vadim/yii/framework/web/helpers/CHtml.php(2529): CComponent->__get('repeat_password')
#1 /home/vadim/yii/framework/web/helpers/CHtml.php(2252): CHtml::resolveValue(Object(UserForm), 'repeat_password')
#2 /home/vadim/yii/framework/web/helpers/CHtml.php(1628): CHtml::activeInputField('password', Object(UserForm), 'repeat_password', Array)
#3 /home/vadim/projects/www/yiitest/protected/views/user/register.php(19): CHtml::activePasswordField(Object(UserForm), 'repeat_password')
#4 /home/vadim/yii/framework/web/CBaseController.php(126): require('/home/vadim/pro...')
#5 /home/vadim/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal('/home/vadim/pro...', Array, true)
#6 /home/vadim/yii/framework/web/CController.php(869): CBaseController->renderFile('/home/vadim/pro...', Array, true)
#7 /home/vadim/yii/framework/web/CController.php(782): CController->renderPartial('register', Array, true)
#8 /home/vadim/projects/www/yiitest/protected/controllers/UserController.php(25): CController->render('register', Array)
#9 /home/vadim/yii/framework/web/actions/CInlineAction.php(49): UserController->actionRegister()
#10 /home/vadim/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#11 /home/vadim/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#12 /home/vadim/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 /home/vadim/yii/framework/web/CWebApplication.php(282): CController->run('register')
#14 /home/vadim/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('user/register')
#15 /home/vadim/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#16 /home/vadim/projects/www/yiitest/index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/register
---
2014/02/17 14:12:06 [warning] [application] Failed to set unsafe attribute "repeatPassword" of "User".
in /home/vadim/projects/www/yiitest/protected/controllers/UserController.php (19)
in /home/vadim/projects/www/yiitest/index.php (13)
2014/02/17 14:30:50 [warning] [application] Failed to set unsafe attribute "repeatPassword" of "User".
in /home/vadim/projects/www/yiitest/protected/controllers/UserController.php (19)
in /home/vadim/projects/www/yiitest/index.php (13)
2014/02/17 14:31:01 [warning] [application] Failed to set unsafe attribute "repeatPassword" of "User".
in /home/vadim/projects/www/yiitest/protected/controllers/UserController.php (19)
in /home/vadim/projects/www/yiitest/index.php (13)
2014/02/17 14:31:11 [warning] [application] Failed to set unsafe attribute "repeatPassword" of "User".
in /home/vadim/projects/www/yiitest/protected/controllers/UserController.php (19)
in /home/vadim/projects/www/yiitest/index.php (13)
2014/02/17 14:31:20 [warning] [application] Failed to set unsafe attribute "repeatPassword" of "User".
in /home/vadim/projects/www/yiitest/protected/controllers/UserController.php (19)
in /home/vadim/projects/www/yiitest/index.php (13)
2014/02/17 14:32:41 [warning] [application] Failed to set unsafe attribute "repeatPassword" of "User".
in /home/vadim/projects/www/yiitest/protected/controllers/UserController.php (19)
in /home/vadim/projects/www/yiitest/index.php (13)
2014/02/17 14:34:24 [warning] [application] Failed to set unsafe attribute "repeatPassword" of "User".
in /home/vadim/projects/www/yiitest/protected/controllers/UserController.php (19)
in /home/vadim/projects/www/yiitest/index.php (13)
2014/02/17 14:34:31 [warning] [application] Failed to set unsafe attribute "repeatPassword" of "User".
in /home/vadim/projects/www/yiitest/protected/controllers/UserController.php (19)
in /home/vadim/projects/www/yiitest/index.php (13)
2014/02/17 14:35:23 [warning] [application] Failed to set unsafe attribute "repeatPassword" of "User".
in /home/vadim/projects/www/yiitest/protected/controllers/UserController.php (19)
in /home/vadim/projects/www/yiitest/index.php (13)
2014/02/17 14:41:18 [warning] [application] Failed to set unsafe attribute "repeatPassword" of "User".
in /home/vadim/projects/www/yiitest/protected/controllers/UserController.php (19)
in /home/vadim/projects/www/yiitest/index.php (13)
2014/02/17 14:42:31 [warning] [application] Failed to set unsafe attribute "repeatPassword" of "User".
in /home/vadim/projects/www/yiitest/protected/controllers/UserController.php (19)
in /home/vadim/projects/www/yiitest/index.php (13)
2014/02/17 14:43:01 [warning] [application] Failed to set unsafe attribute "repeatPassword" of "User".
in /home/vadim/projects/www/yiitest/protected/controllers/UserController.php (19)
in /home/vadim/projects/www/yiitest/index.php (13)
2014/02/17 14:43:03 [warning] [application] Failed to set unsafe attribute "repeatPassword" of "User".
in /home/vadim/projects/www/yiitest/protected/controllers/UserController.php (19)
in /home/vadim/projects/www/yiitest/index.php (13)
2014/02/17 14:44:20 [warning] [application] Failed to set unsafe attribute "repeatPassword" of "User".
in /home/vadim/projects/www/yiitest/protected/controllers/UserController.php (19)
in /home/vadim/projects/www/yiitest/index.php (13)
2014/02/17 15:03:34 [error] [exception.CException] exception 'CException' with message 'CWebApplication and its behaviors do not have a method or closure named "redirect".' in /home/vadim/yii/framework/base/CComponent.php:266
Stack trace:
#0 /home/vadim/projects/www/yiitest/protected/controllers/UserController.php(33): CComponent->__call('redirect', Array)
#1 /home/vadim/projects/www/yiitest/protected/controllers/UserController.php(33): CWebApplication->redirect('index')
#2 /home/vadim/yii/framework/web/actions/CInlineAction.php(49): UserController->actionLogin()
#3 /home/vadim/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /home/vadim/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /home/vadim/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /home/vadim/yii/framework/web/CWebApplication.php(282): CController->run('login')
#7 /home/vadim/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('user/login')
#8 /home/vadim/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /home/vadim/projects/www/yiitest/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/login
HTTP_REFERER=http://localhost:8000/login
---
2014/02/17 15:04:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index".' in /home/vadim/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /home/vadim/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('index')
#1 /home/vadim/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /home/vadim/projects/www/yiitest/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index
HTTP_REFERER=http://localhost:8000/login
---
2014/02/17 15:04:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index".' in /home/vadim/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /home/vadim/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('index')
#1 /home/vadim/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /home/vadim/projects/www/yiitest/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index
---
2014/02/17 15:05:04 [warning] [application] Failed to set unsafe attribute "repeatPassword" of "User".
in /home/vadim/projects/www/yiitest/protected/controllers/UserController.php (19)
in /home/vadim/projects/www/yiitest/index.php (13)
